# Generated by Django 4.2 on 2023-04-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('last_name', models.CharField(max_length=20, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Izdelie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izdelie', models.CharField(max_length=20, verbose_name='Изделие')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('izdelie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='new.izdelie')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
